spring:
    application:
        name: HouseRent
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/houserent
        username: postgres
        password: 2020

    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true

server:
    error:
        include-stacktrace: always
    port: 8089

app:
    jwt:
        secret: air
