spring:
    application:
        name: HouseRent

    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/airbnb
        username: postgres
        password: 2020
        password: 1234

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true


server:
    error:
        include-stacktrace: always

app:
    jwt:
        secret: air
